extensions:
  - kafka_run_helper.py
name: Kafka run helper schema
desc: This schema help validating configuration for the helper
type: map
mapping:
  version:
    type: str
    func: schema_validation
    pattern: ^([0-9]+)\.([0-9]+)\.([0-9]+)$
    required: True
  environment:
    type: str
    pattern: ^([a-z]+)$
    required: True
  service:
    type: str
    required: True
  kafka:
    type: map
    required: True
    mapping:
      bootstrap_server:
        include: config
        required: True
      keystore:
        include: keystore
        required: True
      truststore:
        include: truststore
        required: True
  schema_registry:
    type: map
    required: True
    mapping:
      user_name:
        include: config
        required: True
      password:
        include: config
        required: True
      url:
        include: config
        required: True

schema;config:
  type: map
  matching-rule: any
  range:
    min: 1
    max: 1
  mapping:
    regex;(^value$):
      include: value
    regex;(^kubernetes$):
      include: kubernetes
    regex;(^google_cloud_secret_manager$):
      include: google_cloud_secret_manager
    regex;(^file$):
      include: file

schema;keystore:
  type: map
  matching-rule: any
  range:
    min: 1
    max: 1
  mapping:
    regex;(^binary$):
      include: keystore_binary
    regex;(^generate$):
      include: keystore_certificate

schema;keystore_binary:
  type: map
  mapping:
    keystore:
      include: config
      required: True
    password:
      include: config
      required: True

schema;keystore_certificate:
  type: map
  mapping:
    client_private_key:
      include: config
      required: True
    client_certificate:
      include: config
      required: True

schema;truststore:
  type: map
  matching-rule: any
  range:
    min: 1
    max: 1
  mapping:
    regex;(^binary$):
      include: truststore_binary
    regex;(^generate$):
      include: truststore_certificate

schema;truststore_binary:
  type: map
  mapping:
    truststore:
      include: config
      required: True
    password:
      include: config
      required: True

schema;truststore_certificate:
  type: map
  mapping:
    ca_certificate:
      include: config
      required: True
